sudo: false
language: node_js
node_js:
  - '4'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-pixi-babel' ]; then cd .. && eval "mv $currentfolder generator-pixi-babel" && cd generator-pixi-babel; fi
